"""Parity against golden values generated by executing the ComfyUI implementation.

This is the strongest validation tier available on a Mac: the fixture is the output
of a real reference run, not a transcription. Everything here is weightless.
"""

from __future__ import annotations

import json
import math
import pytest

from mlx_h3 import layout

pytestmark = pytest.mark.fixture


@pytest.fixture(scope="module")
def golden(local_file) -> dict:
    path = local_file("MLX_H3_LAYOUT_FIXTURE")
    return json.loads(path.read_text())


def test_constants(golden):
    c = golden["constants"]
    assert tuple(c["FRAME_PER_TOKEN"]) == layout.FRAME_PER_TOKEN
    assert c["FRAME_RESCALE"] == layout.FRAME_RESCALE
    assert c["VISUAL_COND_TIMESTEP"] == layout.VISUAL_COND_TIMESTEP
    assert c["AUDIO_COND_TIMESTEP"] == layout.AUDIO_COND_TIMESTEP
    assert c["CANVAS_MULTIPLE"] == layout.CANVAS_MULTIPLE
    assert c["BASE_SHORT_EDGE"] == layout.BASE_SHORT_EDGE
    assert c["MAX_PIXELS"] == layout.MAX_PIXELS
    assert c["FPS"] == layout.FPS
    assert c["AUDIO_LATENT_FPS"] == layout.AUDIO_LATENT_FPS
    assert c["sigma_shift_video"] == layout.SIGMA_SHIFT_VIDEO
    assert c["sigma_shift_audio"] == layout.SIGMA_SHIFT_AUDIO


def test_frame_grid_alignment(golden):
    for case in golden["frame_grid"]:
        aligned = layout.align_frame_count(case["requested"])
        assert aligned == case["aligned"], case
        assert layout.video_latent_t(aligned) == case["latent_t"], case
        assert aligned % 17 == 5


def test_temporal_shape(golden):
    for case in golden["temporal_shape"]:
        got = layout.temporal_shape(case["length"])
        assert got == (case["frame_count"], case["latent_t"], case["audio_t"]), case


def test_adapt_canvas(golden):
    for case in golden["adapt_canvas"]:
        got = layout.adapt_canvas(case["in_w"], case["in_h"])
        assert got == (case["out_w"], case["out_h"]), case
        assert got[0] % layout.CANVAS_MULTIPLE == 0
        assert got[1] % layout.CANVAS_MULTIPLE == 0


def test_sigma_schedule(golden):
    for case in golden["sigma_schedule"]:
        sv = case["sigma_v"]
        assert layout.audio_sigma(sv) == pytest.approx(case["sigma_a"], rel=1e-12)
        assert layout.audio_slope(sv) == pytest.approx(case["slope"], rel=1e-12)


def test_sigma_shift_roundtrip(golden):
    """Shifting to the audio schedule and back must be the identity."""
    for case in golden["sigma_schedule"]:
        sv = case["sigma_v"]
        back = layout.time_shift_sigma(
            layout.audio_sigma(sv), layout.SIGMA_SHIFT_AUDIO, layout.SIGMA_SHIFT_VIDEO
        )
        assert back == pytest.approx(sv, rel=1e-12)


def test_video_t_grid(golden):
    for case in golden["video_t_grid"]:
        grid = layout.video_t_grid(case["n"], case["origin"])
        assert len(grid) == case["n"], case
        for got, want in zip(grid, case["grid"], strict=True):
            assert got == pytest.approx(want, rel=1e-12, abs=1e-12)
        spans = layout.video_t_spans(case["n"])
        assert sum(spans) == pytest.approx(case["spans_sum"], rel=1e-12)


def test_frame_position_grid(golden):
    for case in golden["frame_position_grid"]:
        grid, w_axis = layout.frame_grid(case["latent_h"], case["latent_w"])
        assert len(grid) == case["rows"], case
        assert len(w_axis) == case["latent_w"] // 2

        assert grid[0][0] == pytest.approx(case["frame_first"][0], rel=1e-12)
        assert grid[0][1] == pytest.approx(case["frame_first"][1], rel=1e-12)
        assert grid[-1][0] == pytest.approx(case["frame_last"][0], rel=1e-12)
        assert grid[-1][1] == pytest.approx(case["frame_last"][1], rel=1e-12)

        total = math.fsum(h + w for h, w in grid)
        assert total == pytest.approx(case["frame_sum"], rel=1e-9)

        assert w_axis[0] == pytest.approx(case["w_grid_first"], rel=1e-12)
        assert w_axis[-1] == pytest.approx(case["w_grid_last"], rel=1e-12)


# --- packed layout --------------------------------------------------------
#
# The fixture identifies each case only by name, so the conditioning that
# produced it is reconstructed here. Both fl2va cases anchor keyframes; neither
# exercises the ref2va blocks, which stay unvalidated.

CONDITIONING = {
    "dev_t2va": {},
    "spec_t2va": {},
    "dev_fl2va_first": {"keyframes": (layout.Keyframe(0),)},
    "dev_fl2va_both": {"keyframes": (layout.Keyframe(0), layout.Keyframe(55))},
}


def build(case: dict) -> layout.PackedLayout:
    return layout.pack(
        text_len=case["text_len"],
        latent_t=case["latent_t"],
        latent_h=case["latent_h"],
        latent_w=case["latent_w"],
        audio_t=case["audio_t"],
        frame_count=case["frame_count"],
        **CONDITIONING[case["name"]],
    )


def test_packed_layout_shapes(golden):
    """Case shapes must follow from the requested clip, not from the fixture.

    The canvases are given, not derived: `dev` is a deliberately small 864x480
    iteration config, so it is not an `adapt_canvas` output the way `spec` is.
    """
    for case in golden["packed_layout"]:
        frame_count, latent_t, audio_t = layout.temporal_shape(case["frame_count"])
        assert frame_count == case["frame_count"], case["name"]
        assert latent_t == case["latent_t"], case["name"]
        assert audio_t == case["audio_t"], case["name"]
        assert layout.latent_canvas(case["width"], case["height"]) == (
            case["latent_h"],
            case["latent_w"],
        ), case["name"]


def test_packed_layout_segments(golden):
    for case in golden["packed_layout"]:
        got = build(case)
        assert got.seq_len == case["seq_len"], case["name"]
        assert len(got.positions) == case["seq_len"], case["name"]

        want = [tuple(s) for s in case["segments"]]
        assert [(s.start, s.stop, s.kind) for s in got.segments] == want, case["name"]

        # Contiguous cover, no gaps or overlaps.
        assert got.segments[0].start == 0
        assert got.segments[-1].stop == got.seq_len
        for prev, nxt in zip(got.segments, got.segments[1:], strict=False):
            assert prev.stop == nxt.start, case["name"]


def test_packed_layout_positions(golden):
    """Sum and index-weighted sum together pin values and ordering.

    A plain column sum is permutation-invariant, so swapping the two stereo
    channels' pinned w coordinates would slip past it. The 1..S weights make the
    second checksum order-sensitive.
    """
    for case in golden["packed_layout"]:
        got = build(case)
        name = case["name"]

        for axis in range(3):
            assert got.positions[0][axis] == pytest.approx(
                case["pos_first"][axis], rel=1e-12, abs=1e-12
            ), name
            assert got.positions[-1][axis] == pytest.approx(
                case["pos_last"][axis], rel=1e-12, abs=1e-12
            ), name

            column = [row[axis] for row in got.positions]
            assert math.fsum(column) == pytest.approx(
                case["pos_sum"][axis], rel=1e-9, abs=1e-9
            ), name
            weighted = math.fsum(i * v for i, v in enumerate(column, start=1))
            assert weighted == pytest.approx(
                case["pos_weighted"][axis], rel=1e-9, abs=1e-9
            ), name

        for seg, want in zip(got.segments, case["seg_first_pos"], strict=True):
            for axis in range(3):
                assert got.positions[seg.start][axis] == pytest.approx(
                    want[axis], rel=1e-12, abs=1e-12
                ), (name, seg.kind)


def test_packed_layout_update_masks(golden):
    for case in golden["packed_layout"]:
        got = build(case)
        name = case["name"]
        assert sum(got.img_update) == case["img_update_true"], name
        assert sum(got.audio_update) == case["audio_update_true"], name

        # Every img/audio row belongs to exactly one segment of that stream.
        img_kinds = {"cond", "ref_img", "video"}
        audio_kinds = {"ref_audio", "audio"}
        assert len(got.img_update) == sum(
            len(s) for s in got.segments if s.kind in img_kinds
        ), name
        assert len(got.audio_update) == sum(
            len(s) for s in got.segments if s.kind in audio_kinds
        ), name

        # Conditioning always precedes target, so the mask is a partition.
        assert got.img_update == sorted(got.img_update), name
        assert got.audio_update == sorted(got.audio_update), name
