"""Weightless layout and schedule primitives for MiniMax-H3.

Every value produced here is checked against golden values that were generated by
*executing* the ComfyUI reference (`comfy/ldm/minimax/model.py`,
`comfy_extras/nodes_minimax_h3.py`). This is the only validation tier backed by a
real reference run rather than a transcription, so it is where correctness is
cheapest to establish. See tests/test_layout.py.

Grids are built with Python floats (IEEE double) rather than mx.array: MLX has no
GPU float64, and position grids feed rotary encoding where the reference is exact
in double. These are setup-time values computed once per generation, so the cost is
irrelevant; conversion to float32 happens at the boundary via `to_mlx`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import mlx.core as mx

# --- canvas ---------------------------------------------------------------

CANVAS_MULTIPLE = 32
BASE_SHORT_EDGE = 768
MAX_PIXELS = 768 * 1344

#: Video VAE spatial compression: space_down [2,2,2,2,1,1] in its source config.
#: 16, not the 8 most video VAEs use -- with the DiT's 2x2 patch on top, one
#: attention row covers a 32x32 pixel block.
VAE_SPATIAL_RATIO = 16

# --- temporal -------------------------------------------------------------

FPS = 24
AUDIO_LATENT_FPS = 40

#: Frames covered by each latent token within a 5-token group; the group spans
#: 1 + 4 + 4 + 4 + 4 = 17 frames, which is why frame counts align to 17n + 5.
FRAME_PER_TOKEN = (1, 4, 4, 4, 4)
FRAME_RESCALE = 5.0 / 3.0

# --- schedule -------------------------------------------------------------

SIGMA_SHIFT_VIDEO = 12.0
SIGMA_SHIFT_AUDIO = 3.0

VISUAL_COND_TIMESTEP = 0.999
AUDIO_COND_TIMESTEP = 1.0


# --- frame counts ---------------------------------------------------------


def align_frame_count(n: int) -> int:
    """Round a frame count up to the next value the video VAE can decode.

    Valid counts satisfy ``n % 17 == 5``.
    """
    while n % 17 != 5:
        n += 1
    return n


def video_latent_t(frame_count: int) -> int:
    """Latent temporal length for an already-aligned frame count."""
    return 2 if frame_count <= 5 else ((frame_count - 5) // 17) * 5 + 2


def temporal_shape(length: int) -> tuple[int, int, int]:
    """``length`` requested frames -> (frame_count, latent_t, audio_t)."""
    frame_count = align_frame_count(max(5, length))
    duration = frame_count / FPS
    return frame_count, video_latent_t(frame_count), round(duration * AUDIO_LATENT_FPS)


def latent_canvas(width: int, height: int) -> tuple[int, int]:
    """Pixel canvas -> the video VAE's latent spatial dims (latent_h, latent_w)."""
    return height // VAE_SPATIAL_RATIO, width // VAE_SPATIAL_RATIO


def adapt_canvas(width: int, height: int) -> tuple[int, int]:
    """768-short-edge canvas with a 768*1344 area cap, per-axis rounded to 32."""
    ratio = width / height
    if ratio >= 1.0:
        nom_w, nom_h = BASE_SHORT_EDGE * ratio, float(BASE_SHORT_EDGE)
    else:
        nom_w, nom_h = float(BASE_SHORT_EDGE), BASE_SHORT_EDGE / ratio
    if nom_w * nom_h > MAX_PIXELS:
        s = math.sqrt(MAX_PIXELS / (nom_w * nom_h))
        nom_w, nom_h = nom_w * s, nom_h * s
    return (
        max(CANVAS_MULTIPLE, round(nom_w / CANVAS_MULTIPLE) * CANVAS_MULTIPLE),
        max(CANVAS_MULTIPLE, round(nom_h / CANVAS_MULTIPLE) * CANVAS_MULTIPLE),
    )


# --- sigma schedules ------------------------------------------------------
#
# Video and audio latents ride different shifted schedules but are denoised by a
# single transformer call per step. Converting between them means inverting one
# shift back to the shared base grid and re-applying the other.


def time_shift_sigma(sigma: float, from_shift: float, to_shift: float) -> float:
    """Re-express ``sigma`` from one shifted schedule onto another."""
    base = sigma / (from_shift + sigma * (1.0 - from_shift))
    return to_shift * base / (1.0 + (to_shift - 1.0) * base)


def time_shift_slope(sigma: float, from_shift: float, to_shift: float) -> float:
    """``d(sigma_to)/d(sigma_from)`` at the same base-grid point.

    Retained because the executed layout fixture pins this schedule primitive and
    the ComfyUI adapter uses it to integrate both streams on one grid. The native
    sampler instead steps video and audio on their own finite sigma schedules.
    """
    base = sigma / (from_shift + sigma * (1.0 - from_shift))
    num = to_shift * (1.0 + (from_shift - 1.0) * base) ** 2
    den = from_shift * (1.0 + (to_shift - 1.0) * base) ** 2
    return num / den


def audio_sigma(sigma_video: float) -> float:
    """Audio sigma matching a point on the video schedule."""
    return time_shift_sigma(sigma_video, SIGMA_SHIFT_VIDEO, SIGMA_SHIFT_AUDIO)


def audio_slope(sigma_video: float) -> float:
    """Velocity rescale for the audio stream at a point on the video schedule."""
    return time_shift_slope(sigma_video, SIGMA_SHIFT_VIDEO, SIGMA_SHIFT_AUDIO)


# --- position grids -------------------------------------------------------


def _axis_from_sqrt_area(dim: int, patch: int, sqrt_area: float) -> list[float]:
    """Area-normalized coordinates along one spatial axis.

    Equivalent to ``linspace((1 - r) / 2, (1 + r) / 2, dim // patch, endpoint=False) * 32``
    with ``r = dim / sqrt_area``.
    """
    ratio = dim / sqrt_area
    n = dim // patch
    step = ratio / n
    base = (1.0 - ratio) / 2.0
    return [(i * step + base) * 32.0 for i in range(n)]


def frame_grid(h: int, w: int) -> tuple[list[tuple[float, float]], list[float]]:
    """(h, w) coordinates of one latent frame's 2x2-patch rows, row-major.

    Returns the grid and the width axis (needed to pin audio rows to the extremes).
    """
    area = math.sqrt(h * w)
    h_axis = _axis_from_sqrt_area(h, 2, area)
    w_axis = _axis_from_sqrt_area(w, 2, area)
    return [(hh, ww) for hh in h_axis for ww in w_axis], w_axis


def video_t_spans(n: int) -> list[float]:
    """Temporal extent of each of ``n`` latent tokens."""
    return [FRAME_RESCALE * FRAME_PER_TOKEN[k % 5] for k in range(n)]


def video_t_grid(n: int, origin: float) -> list[float]:
    """Temporal coordinate of each latent token: ``origin`` + exclusive cumsum."""
    out, acc = [], float(origin)
    for span in video_t_spans(n):
        out.append(acc)
        acc += span
    return out


def audio_grid(
    cursor: float, t: int, w_low: float, w_high: float
) -> list[tuple[float, float, float]]:
    """Channel-major stereo audio rows: ``2 * t`` rows of (t, h, w).

    ``t`` advances one unit per latent frame, ``h`` stays 0, and ``w`` is pinned to
    opposite extremes of the spatial grid per stereo channel.
    """
    left = [(cursor + i, 0.0, w_low) for i in range(t)]
    right = [(cursor + i, 0.0, w_high) for i in range(t)]
    return left + right


def video_grid(
    vt: int, frame: list[tuple[float, float]], cursor: float
) -> list[tuple[float, float, float]]:
    """Video rows: ``vt`` latent frames x ``len(frame)`` patch rows, of (t, h, w)."""
    ts = video_t_grid(vt, cursor)
    return [(t, hh, ww) for t in ts for hh, ww in frame]


# --- packed sequence ------------------------------------------------------
#
# H3 denoises video and audio jointly inside ONE sequence under full self-
# attention, so the whole clip is laid out as a flat list of rows. The order is
# fixed: text first, then conditioning blocks, then the target audio and target
# video always last. Rows carry no modality field of their own -- position in
# the sequence is the encoding, and the segment table is what recovers it.
#
# Segments are contiguous, which is the property everything downstream leans on:
# the DiT slices instead of gathering, and adaLN modulation is applied per
# segment rather than per token. The reference builds `img_pos`/`audio_pos`
# index arrays alongside, but never reads them in its own forward pass, so they
# are omitted here.


@dataclass(frozen=True)
class Segment:
    """A contiguous run of rows sharing one modality and one timestep class."""

    start: int
    stop: int
    kind: str

    def __len__(self) -> int:
        return self.stop - self.start


@dataclass(frozen=True)
class Keyframe:
    """An fl2va anchor. Only the first and last target frames can be anchored."""

    frame_index: int


@dataclass(frozen=True)
class RefImage:
    latent_h: int
    latent_w: int


@dataclass(frozen=True)
class RefAudio:
    audio_t: int


@dataclass(frozen=True)
class RefVideo:
    latent_t: int
    latent_h: int
    latent_w: int
    audio_t: int = 0


@dataclass(frozen=True)
class PackedLayout:
    """Static structure of one packed sequence: shape plus conditioning signature.

    Depends on nothing but shapes, so it is built once per generation and reused
    across every denoising step.
    """

    seq_len: int
    segments: tuple[Segment, ...]
    positions: list[tuple[float, float, float]]
    img_cond_rows: int
    img_target_rows: int
    audio_cond_rows: int
    audio_target_rows: int
    signature: tuple[int, int, int, int, int]

    # Conditioning rows always precede target rows within each stream, so the
    # reference's boolean update masks are a partition, not a scatter: the two
    # sources concatenate. The masks are reconstructed here only to check that
    # invariant against the reference.

    @property
    def img_update(self) -> list[bool]:
        return [False] * self.img_cond_rows + [True] * self.img_target_rows

    @property
    def audio_update(self) -> list[bool]:
        return [False] * self.audio_cond_rows + [True] * self.audio_target_rows

    def kind_slice(self, kind: str) -> list[Segment]:
        return [s for s in self.segments if s.kind == kind]


def pack(
    *,
    text_len: int,
    latent_t: int,
    latent_h: int,
    latent_w: int,
    audio_t: int,
    keyframes: tuple[Keyframe, ...] = (),
    refs: tuple[RefImage | RefAudio | RefVideo, ...] = (),
    frame_count: int | None = None,
) -> PackedLayout:
    """Lay out one packed sequence.

    ``keyframes`` (fl2va) and ``refs`` (ref2va) are mutually exclusive in every
    reference path: keyframes reuse the target's own timeline, while refs consume
    their own stretch of it ahead of the target.
    """
    frame, w_axis = frame_grid(latent_h, latent_w)
    frame_rows = len(frame)
    audio_w = (w_axis[0], w_axis[-1])

    segments: list[Segment] = []
    positions: list[tuple[float, float, float]] = []
    row = 0

    def emit(kind: str, rows: list[tuple[float, float, float]]) -> None:
        nonlocal row
        segments.append(Segment(row, row + len(rows), kind))
        positions.extend(rows)
        row += len(rows)

    emit("text", [(float(i), 0.0, 0.0) for i in range(text_len)])

    img_cond_rows = audio_cond_rows = 0
    cursor = float(text_len)

    for kf in keyframes:
        # Keyframe conditioning shares the target's spatial grid and sits at the
        # target time of the frame it anchors, so it does not advance the cursor.
        if kf.frame_index == 0:
            cond_t = float(text_len)
        elif frame_count is not None and kf.frame_index == frame_count - 1:
            cond_t = float(text_len) + sum(video_t_spans(latent_t)) - FRAME_RESCALE
        else:
            raise ValueError(
                f"keyframe at frame {kf.frame_index} is neither first nor last "
                f"of {frame_count}; only those two anchors exist"
            )
        emit("cond", [(cond_t, hh, ww) for hh, ww in frame])
        img_cond_rows += frame_rows

    for blk in refs:
        # Reference blocks lay claim to the timeline ahead of the target, each
        # advancing the cursor by its own duration.
        if isinstance(blk, RefImage):
            r_frame, _ = frame_grid(blk.latent_h, blk.latent_w)
            emit("ref_img", [(cursor, hh, ww) for hh, ww in r_frame])
            img_cond_rows += len(r_frame)
            cursor += 1.0
        elif isinstance(blk, RefAudio):
            if blk.audio_t > 0:
                emit("ref_audio", audio_grid(cursor, blk.audio_t, *audio_w))
                audio_cond_rows += blk.audio_t * 2
            cursor += float(blk.audio_t)
        elif isinstance(blk, RefVideo):
            # A block's audio rows pack immediately before its video rows, both
            # anchored at the same cursor.
            r_frame, r_w_axis = frame_grid(blk.latent_h, blk.latent_w)
            if blk.audio_t > 0:
                emit(
                    "ref_audio",
                    audio_grid(cursor, blk.audio_t, r_w_axis[0], r_w_axis[-1]),
                )
                audio_cond_rows += blk.audio_t * 2
            emit("ref_img", video_grid(blk.latent_t, r_frame, cursor))
            img_cond_rows += blk.latent_t * len(r_frame)
            cursor += max(float(blk.audio_t), sum(video_t_spans(blk.latent_t)))
        else:
            raise TypeError(f"unknown reference block {blk!r}")

    emit("audio", audio_grid(cursor, audio_t, *audio_w))
    emit("video", video_grid(latent_t, frame, cursor))

    return PackedLayout(
        seq_len=row,
        segments=tuple(segments),
        positions=positions,
        img_cond_rows=img_cond_rows,
        img_target_rows=latent_t * frame_rows,
        audio_cond_rows=audio_cond_rows,
        audio_target_rows=audio_t * 2,
        signature=(text_len, latent_t, latent_h, latent_w, audio_t),
    )


# --- interop --------------------------------------------------------------


def to_mlx(rows: list[tuple[float, ...]], dtype: mx.Dtype = mx.float32) -> mx.array:
    """Convert a double-precision grid to an MLX array at the compute dtype."""
    return mx.array(rows, dtype=dtype)
